---
- name: Verificar y ejecutar reinicio en servidores Red Hat
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Verificar si el sistema requiere reinicio (Red Hat 6,7)
      when: ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7"
      shell: "[ -f /var/run/reboot-required ] && echo 'reboot required' || echo 'no reboot required'"
      register: reboot_required_rh67
      changed_when: false

    - name: Verificar si el sistema requiere reinicio (Red Hat 8,9)
      when: ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"
      shell: "needs-restarting -r >/dev/null 2>&1 && echo 'no reboot required' || echo 'reboot required'"
      register: reboot_required_rh89
      changed_when: false

    - name: Mostrar estado de reinicio requerido
      debug:
        msg: "El sistema requiere reinicio"
      when: (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7") and "'reboot required' in reboot_required_rh67.stdout"
        or (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9") and "'reboot required' in reboot_required_rh89.stdout"

    - name: Reiniciar el sistema si es necesario
      reboot:
        msg: "Reinicio iniciado por Ansible debido a actualizaciones del sistema"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30
      when: (ansible_distribution_major_version == "6" or ansible_distribution_major_version == "7") and "'reboot required' in reboot_required_rh67.stdout"
        or (ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9") and "'reboot required' in reboot_required_rh89.stdout"
