---
- name: Actualizar Red Hat, SUSE y Ubuntu y verificar si requiere reinicio
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Registrar distribución
      debug:
        msg: "Distribución detectada: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

    - name: Actualizar RedHat/CentOS 6/7/8/9
      when: ansible_os_family == "RedHat"
      package:
        name: "*"
        state: latest

    - name: Actualizar SUSE 12/15
      when: ansible_distribution == "SLES" or ansible_distribution == "SUSE"
      command: zypper -n update
      register: zypper_out
      changed_when: "'Nothing to do' not in zypper_out.stdout"

    - name: Actualizar Ubuntu
      when: ansible_distribution == "Ubuntu"
      apt:
        upgrade: dist
        update_cache: yes

    - name: Verificar si RedHat requiere reinicio
      when: ansible_os_family == "RedHat"
      stat:
        path: /var/run/reboot-required
      register: reboot_required_rh

    - name: Verificar si Ubuntu requiere reinicio
      when: ansible_distribution == "Ubuntu"
      stat:
        path: /var/run/reboot-required
      register: reboot_required_ubuntu

    - name: Verificar si SUSE requiere reinicio
      when: ansible_distribution in ["SLES", "SUSE"]
      shell: 'zypper ps -s | grep "You may wish to restart"'
      register: reboot_required_suse
      ignore_errors: yes

    - name: Reiniciar si es necesario (RedHat)
      when: reboot_required_rh.stat.exists
      reboot:

    - name: Reiniciar si es necesario (Ubuntu)
      when: reboot_required_ubuntu.stat.exists
      reboot:

    - name: Reiniciar si es necesario (SUSE)
      when: reboot_required_suse.stdout is search("restart")
      reboot:

    - name: Registrar resultado de reinicio en log
      copy:
        dest: "/var/log/ansible_reboot_check.log"
        content: |
          Host: {{ inventory_hostname }}
          Fecha: {{ ansible_date_time.date }} {{ ansible_date_time.time }}
          Requiere reinicio: {{
            (reboot_required_rh.stat.exists | default(false)) or
            (reboot_required_ubuntu.stat.exists | default(false)) or
            (reboot_required_suse.stdout is search("restart") | default(false))
          }}
          Reiniciado automáticamente: Sí
      when: inventory_hostname is defined
