---
- name: Verificar si los sistemas requieren reinicio
  hosts: all
  become: yes
  tasks:
    - name: Verificar reinicio requerido en Red Hat/CentOS 6/7/8/9
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_redhat
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

    - name: Verificar reinicio requerido en SUSE 12/15
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_suse
      when: ansible_distribution == "SUSE" or ansible_distribution == "SLES"

    - name: Verificar reinicio requerido en Ubuntu
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_ubuntu
      when: ansible_distribution == "Ubuntu"

    - name: Verificar mediante needrestart en sistemas basados en Debian/Ubuntu
      ansible.builtin.command: needrestart -b -r l
      register: needrestart_check
      ignore_errors: yes
      changed_when: false
      when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

    - name: Verificar mediante needs-restarting en RHEL/CentOS
      ansible.builtin.command: needs-restarting -r
      register: needs_restarting_check
      ignore_errors: yes
      changed_when: false
      when: ansible_distribution == "RedHat" or ansible_distribution == "CentOS"

    - name: Mostrar resultados
      ansible.builtin.debug:
        msg: |
          Distribución: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Requiere reinicio:
          {% if ansible_distribution == "RedHat" or ansible_distribution == "CentOS" %}
            {% if needs_restarting_check.rc == 1 %}SÍ{% else %}NO{% endif %} (needs-restarting)
            {% if reboot_required_redhat.stat.exists %}SÍ (reboot-required file){% endif %}
          {% elif ansible_distribution == "SUSE" or ansible_distribution == "SLES" %}
            {% if reboot_required_suse.stat.exists %}SÍ{% else %}NO{% endif %} (reboot-required file)
          {% elif ansible_distribution == "Ubuntu" %}
            {% if reboot_required_ubuntu.stat.exists %}SÍ (reboot-required file){% else %}NO{% endif %}
            {% if needrestart_check.rc == 0 %}SÍ (needrestart){% endif %}
          {% endif %}
